site_name: DeclarativeX
site_description: DeclarativeX is a Python library for building declarative APIs.
strict: true
site_url: https://declarativex.dev
use_directory_urls: true

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - content.code.annotate

extra:
  analytics:
    provider: google
    property: G-RZ1VN0YPGC

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Core Concepts:
    - BaseClient: core-concepts/base-client.md
    - HTTP Declaration: core-concepts/http-declaration.md
    - Dependencies: core-concepts/dependencies.md
    - Rate Limiting: core-concepts/rate-limiter.md
    - Middlewares: core-concepts/middlewares.md
    - Mapping errors: core-concepts/error-mappings.md
    - Auto retry: core-concepts/auto-retry.md
    - Auth: core-concepts/auth.md
    - GraphQL: core-concepts/graphql.md
  - API:
    - Models: api/models.md
    - Exceptions: api/exceptions.md
  - Compatibility: compatibility.md
  - Testing: testing.md
  - Contributing: contributing.md
  - License: license.md

repo_name: floydya/declarativex
repo_url: https://github.com/floydya/declarativex
edit_uri: edit/main/docs/
plugins:
  - search


markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - abbr
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
