name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run Flake8
        run: |
          output_file="flake8-output.txt"
          poetry run flake8 src/declarativex | tee $output_file

      - name: Annotate code with Flake8 results
        run: |
          output_file="flake8-output.txt"
          python .github/workflows/annotate-flake8.py $output_file

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run Pylint
        run: |
          output_file="pylint-output.txt"
          poetry run pylint src/declarativex | tee $output_file
      - name: Annotate code with Pylint results
        run: |
          output_file="pylint-output.txt"
          python .github/workflows/annotate-pylint.py $output_file

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run mypy
        run: |
          output_file="mypy-output.txt"
          poetry run mypy src/declarativex | tee $output_file
      - name: Annotate code with mypy results
        run: |
          output_file="mypy-output.txt"
          python .github/workflows/annotate-mypy.py $output_file

  pytest:
    runs-on: ubuntu-latest
    needs: [flake8, pylint, mypy]
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        pydantic-version: [">=1,<2", ">=2,<3"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Install Pydantic
        run: poetry add "pydantic${{ matrix.pydantic-version }}"
      - name: Run Pytest
        run: |
          poetry run pytest -n 6 tests/

  coverage:
    runs-on: ubuntu-latest
    needs: [pytest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Set GITHUB_TOKEN with write permissions
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Build coverage file
        run: |
          poetry run pytest -n 6 --junitxml=pytest.xml --cov=src/declarativex tests/ | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
